name: askci-term-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup AskCI Python environment
        run: |
            conda create --quiet --name askci
            conda install beautifulsoup4 markdown lxml

      - name: Run tests
        run: |

          # activate conda env
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate askci
          
          # run tests
          python .github/test_markdown.py
