name: request-review

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Update README.md
      run: |
        jq --raw-output .client_payload.markdown "${GITHUB_EVENT_PATH}" > README.md
        cat README.md
    - name: Checkout Branch and Open Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_AGAINST: master
        EVENT_NAME: request-review
      run: |
        export EVENT_NAME;
        export BRANCH_AGAINST;
        /bin/bash .github/pull-request.sh;
