name: update-template

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Update Template via Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT_NAME: update-template
        BRANCH_AGAINST: "master"
      run: |
        export EVENT_NAME;
        export BRANCH_AGAINST;
        /bin/bash .github/update-template.sh;

