name: update-template

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Update Template via Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT_NAME: update-template
        BRANCH_AGAINST: "master"
      run: |
        export EVENT_NAME;
        export BRANCH_AGAINST;
        wget https://raw.githubusercontent.com/hpsee/askci-term-template/081cf1f69a38cd70424f172eb47bf4609d4e8db3/.github/update-template.sh;
        chmod +x update-template.sh;
        /bin/bash ./update-template.sh;
